### ISSUE TITLE
Not displaying embedded images in email body. 

### ISSUE THREAD

**Issue by moazam-abbas** [natanfelles/codeigniter-imap#2]
This Imap library is giving complete output and helping a lot in my projects but 1 issue i'm facing. It's not displaying embedded images in email body.

**Comment by natanfelles** [comment]
Hi. Did you tried to set the third param to true?

```php
$this->imap->get_message(25, TRUE, TRUE);
```

Uhmmm... Hahah. [This is not available yet...](https://github.com/natanfelles/codeigniter-imap/blob/master/application/libraries/Imap.php#L183)


But I did it in my local repo. I will update...

**Comment by moazam-abbas** [comment]
Thanks..I'm waiting for your commit. Its really your great effort. 🥇

**Comment by natanfelles** [comment]
Ok. Please do your tests. I was not using this as a general library then something can works wrong.

In the next days I will update this library and launch a version. 

If anything is strangerous in your tests, report all bugs.

**Comment by natanfelles** [comment]
Now is possible to get the embedded images: https://github.com/natanfelles/codeigniter-imap/blob/master/application/libraries/Imap.php#L234

**Comment by moazam-abbas** [comment]
OK..I'm using now this updated file in my current project. I'll update you in couple of days after complete test on live projects.
Thanks

**Comment by moazam-abbas** [comment]
There is Attachment filename issue, I noticed it in old version too...check this attachment array:

                             [0] => Array
                                (
                                    [name] => Thu, 07 Sep 2017 14:28:01 GMT
                                    [size] => 12642
                                    [disposition] => INLINE
                                    [reference] => <3ACC6592-BCA7-483B-A8B9-9059E54B2819>
                                )

                            [1] => Array
                                (
                                    [name] => Thu, 07 Sep 2017 14:28:01 GMT
                                    [size] => 38044
                                    [disposition] => INLINE
                                    [reference] => <2BAB5219-EA1C-409A-B35C-F9C6E66A668F>
                                )

                            [2] => Array
                                (
                                    [name] => Thu, 07 Sep 2017 14:28:01 GMT
                                    [size] => 1225278
                                    [disposition] => ATTACHMENT
                                    [reference] => <9FFD2C7AA544C447B0A039B72B2345CB@eurprd07.prod.outlook.com>
                                )

                            [3] => Array
                                (
                                    [name] => Thu, 07 Sep 2017 14:28:01 GMT
                                    [size] => 41214
                                    [disposition] => ATTACHMENT
                                    [reference] => <2BB6C09F5910ED4B991A8228D04FD70A@eurprd07.prod.outlook.com>
                                )

**Comment by moazam-abbas** [comment]
Still inline images are not visible in body :(

And other issue is Filename which is coming as Timestamp (Thu, 07 Sep 2017 14:28:01 GMT etc)

**Comment by natanfelles** [comment]
I tested on Outlook and the attachments names was the correct filename.

With this [commit](https://github.com/natanfelles/codeigniter-imap/commit/1740132f4baccbd3c3c1d5ad031abe15e5397722) the problem with inline images was fixed here.

The IMAP is a little confusing because it has id, uid and msg_number...

Well, test and let me know.

**Comment by moazam-abbas** [comment]
Hi
Sorry I couldn't check latest file that time...But i'm just checking. Its giving error for me.. something like msg_number error. 
I think you should update your Readme file too with latest instructions. can you plz? :)

Thnaks

**Comment by natanfelles** [comment]
README will be updated.

I will begin to version this library and the methods will be guided by the uid's.
