### ISSUE TITLE
Message:  Unknown: Unexpected characters at end of address: <> (errflg=3)

### ISSUE THREAD

**Issue by tasmanwebsolutions** [natanfelles/codeigniter-imap#5]
I am using codeigniter 3 > When I use this function $this->imap->get_mailbox_size()

I get error Message:  Unknown: Unexpected characters at end of address: <> (errflg=3)

**Comment by natanfelles** [comment]
Will be fixed.

Solution found: https://stackoverflow.com/questions/3378469/how-to-get-rid-of-error-messages-with-phps-imap-fetchstructure#answer-3378628

> I believe the error message is emitted when you call imap_close(), or, in that function's absence, when the script ends. Try calling imap_errors() before that (to clear the error stack).

```php
// This solves
imap_errors();
imap_close($this->stream);
```
